heart:
  api:
    swagger-open: true  #是否开启swagger
    captcha-open: false #是否开启登陆验证码
    sign-open: true #签名机制是否开启
    secret: miyao     #秘钥
server:
  port: 8081
  servlet:
    context-path: /heart_api
spring:
  profiles:
    active: @spring.active@
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB

---
#开发环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beam?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 6000 #超时时间（毫秒）
log:
  path: /home/heart/dev

---
#测试环境
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://59.110.226.231:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 6000
log:
  path: /home/heart/test

---
#生产环境
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 6000
log:
  path: /home/heart/pro
